// prisma/seeds/skins.ts
import { PrismaClient } from "@prisma/client";

interface SkinDefinition {
  slug: string;
  variantSlug: string;
  colorPt: string;
  colorEn: string;
  releaseDate: Date;
  limitedEdition: boolean;
  editionName: string | null;
  material: string;
  finish: string;
  imageUrl: string;
}

export async function createSkins(db: PrismaClient, variants: Record<string, { id: number }>) {
  const skinDefinitions: SkinDefinition[] = [
    // ========================
    // PlayStation 1 (Fat)
    // ========================
    {
      variantSlug: "ps1-fat",
      slug: "ps1-fat-grey",
      colorPt: "Cinza",
      colorEn: "Grey",
      releaseDate: new Date("1994-12-03"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps1-fat-grey.webp",
    },
    {
      variantSlug: "ps1-fat",
      slug: "ps1-fat-net-yaroze",
      colorPt: "Preto Net Yaroze",
      colorEn: "Net Yaroze Black",
      releaseDate: new Date("1997-05-01"),
      limitedEdition: true,
      editionName: "Net Yaroze Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps1-net-yaroze.webp",
    },
    {
      variantSlug: "ps1-fat",
      slug: "ps1-fat-resident-evil",
      colorPt: "Resident Evil Edition",
      colorEn: "Resident Evil Edition",
      releaseDate: new Date("1997-07-25"),
      limitedEdition: true,
      editionName: "Resident Evil",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps1-fat-re.webp",
    },
    {
      variantSlug: "ps1-fat",
      slug: "ps1-fat-lsdj",
      colorPt: "Lemon Sky Dreamcast Japan",
      colorEn: "Lemon Sky Dreamcast Japan",
      releaseDate: new Date("1998-03-01"),
      limitedEdition: true,
      editionName: "LSDJ Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps1-lsdj.webp",
    },

    // ========================
    // PlayStation 1 (Slim - PSOne)
    // ========================
    {
      variantSlug: "ps1-slim",
      slug: "ps1-slim-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2000-07-07"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps1-slim-white.webp",
    },
    {
      variantSlug: "ps1-slim",
      slug: "ps1-slim-smoke",
      colorPt: "Fumaça",
      colorEn: "Smoke",
      releaseDate: new Date("2000-11-15"),
      limitedEdition: true,
      editionName: "Smoke Black",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps1-slim-smoke.webp",
    },
    {
      variantSlug: "ps1-slim",
      slug: "ps1-slim-racing",
      colorPt: "Rally Championship",
      colorEn: "Rally Championship",
      releaseDate: new Date("2001-03-01"),
      limitedEdition: true,
      editionName: "Rally Championship",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps1-rally.webp",
    },
    {
      variantSlug: "ps1-slim",
      slug: "ps1-slim-sakura",
      colorPt: "Sakura Taisen",
      colorEn: "Sakura Taisen",
      releaseDate: new Date("2001-07-12"),
      limitedEdition: true,
      editionName: "Sakura Taisen Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps1-sakura.webp",
    },

    // ========================
    // PlayStation 2 (Fat)
    // ========================
    {
      variantSlug: "ps2-fat",
      slug: "ps2-fat-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2000-03-04"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps2-fat-black.webp",
    },
    {
      variantSlug: "ps2-fat",
      slug: "ps2-fat-satin-silver",
      colorPt: "Prata Cetim",
      colorEn: "Satin Silver",
      releaseDate: new Date("2002-09-01"),
      limitedEdition: true,
      editionName: "Satin Silver Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps2-satin-silver.webp",
    },
    {
      variantSlug: "ps2-fat",
      slug: "ps2-fat-aqua-blue",
      colorPt: "Azul Água",
      colorEn: "Aqua Blue",
      releaseDate: new Date("2003-04-01"),
      limitedEdition: true,
      editionName: "Aqua Blue Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps2-aqua-blue.webp",
    },
    {
      variantSlug: "ps2-fat",
      slug: "ps2-fat-final-fantasy",
      colorPt: "Final Fantasy XI",
      colorEn: "Final Fantasy XI",
      releaseDate: new Date("2004-03-18"),
      limitedEdition: true,
      editionName: "Final Fantasy XI Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps2-ffxi.webp",
    },

    // ========================
    // PlayStation 2 (Slim)
    // ========================
    {
      variantSlug: "ps2-slim",
      slug: "ps2-slim-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2004-11-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps2-slim-black.webp",
    },
    {
      variantSlug: "ps2-slim",
      slug: "ps2-slim-ceramic-white",
      colorPt: "Branco Cerâmico",
      colorEn: "Ceramic White",
      releaseDate: new Date("2005-06-15"),
      limitedEdition: true,
      editionName: "Ceramic White Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps2-ceramic-white.webp",
    },
    {
      variantSlug: "ps2-slim",
      slug: "ps2-slim-pink",
      colorPt: "Rosa",
      colorEn: "Pink",
      releaseDate: new Date("2006-03-01"),
      limitedEdition: true,
      editionName: "Pink Sakura Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps2-pink.webp",
    },
    {
      variantSlug: "ps2-slim",
      slug: "ps2-slim-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("2006-12-01"),
      limitedEdition: true,
      editionName: "24K Gold Limited",
      material: "Plástico ABS com revestimento metálico",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps2-gold.webp",
    },

    // ========================
    // PlayStation 3 (Fat)
    // ========================
    {
      variantSlug: "ps3-fat",
      slug: "ps3-fat-black",
      colorPt: "Preto Brilhante",
      colorEn: "Piano Black",
      releaseDate: new Date("2006-11-11"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps3-fat-black.webp",
    },
    {
      variantSlug: "ps3-fat",
      slug: "ps3-fat-chrome",
      colorPt: "Cromado",
      colorEn: "Chrome",
      releaseDate: new Date("2007-11-01"),
      limitedEdition: true,
      editionName: "Chrome Edition",
      material: "Metalizado",
      finish: "Espelhado",
      imageUrl: "images/skins/sony/ps3-chrome.webp",
    },
    {
      variantSlug: "ps3-fat",
      slug: "ps3-fat-mgs4",
      colorPt: "Metal Gear Solid 4",
      colorEn: "Metal Gear Solid 4",
      releaseDate: new Date("2008-06-12"),
      limitedEdition: true,
      editionName: "MGS4 Guns of the Patriots",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps3-mgs4.webp",
    },
    {
      variantSlug: "ps3-fat",
      slug: "ps3-fat-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2009-01-01"),
      limitedEdition: true,
      editionName: "Ceramic White Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps3-white.webp",
    },

    // ========================
    // PlayStation 3 (Slim)
    // ========================
    {
      variantSlug: "ps3-slim",
      slug: "ps3-slim-matte-black",
      colorPt: "Preto Fosco",
      colorEn: "Matte Black",
      releaseDate: new Date("2009-09-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps3-slim-black.webp",
    },
    {
      variantSlug: "ps3-slim",
      slug: "ps3-slim-red",
      colorPt: "Vermelho Carmim",
      colorEn: "Scarlet Red",
      releaseDate: new Date("2010-09-01"),
      limitedEdition: true,
      editionName: "Scarlet Red Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps3-slim-red.webp",
    },
    {
      variantSlug: "ps3-slim",
      slug: "ps3-slim-blue",
      colorPt: "Azul Oceano",
      colorEn: "Ocean Blue",
      releaseDate: new Date("2010-10-01"),
      limitedEdition: true,
      editionName: "Ocean Blue Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps3-slim-blue.webp",
    },
    {
      variantSlug: "ps3-slim",
      slug: "ps3-slim-god-of-war",
      colorPt: "God of War Saga",
      colorEn: "God of War Saga",
      releaseDate: new Date("2012-08-28"),
      limitedEdition: true,
      editionName: "God of War Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps3-gow.webp",
    },

    // ========================
    // PlayStation 3 (Super Slim)
    // ========================
    {
      variantSlug: "ps3-super-slim",
      slug: "ps3-ss-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2012-09-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps3-ss-black.webp",
    },
    {
      variantSlug: "ps3-super-slim",
      slug: "ps3-ss-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2012-10-01"),
      limitedEdition: true,
      editionName: "White Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps3-ss-white.webp",
    },
    {
      variantSlug: "ps3-super-slim",
      slug: "ps3-ss-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("2013-02-01"),
      limitedEdition: true,
      editionName: "Red Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps3-ss-red.webp",
    },
    {
      variantSlug: "ps3-super-slim",
      slug: "ps3-ss-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("2013-02-01"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps3-ss-blue.webp",
    },

    // ========================
    // PlayStation 4 (Fat)
    // ========================
    {
      variantSlug: "ps4-fat",
      slug: "ps4-fat-black",
      colorPt: "Preto Fosco",
      colorEn: "Matte Black",
      releaseDate: new Date("2013-11-15"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps4-fat-black.webp",
    },
    {
      variantSlug: "ps4-fat",
      slug: "ps4-fat-glacier-white",
      colorPt: "Branco Gelo",
      colorEn: "Glacier White",
      releaseDate: new Date("2014-09-09"),
      limitedEdition: true,
      editionName: "Destiny Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps4-fat-white.webp",
    },
    {
      variantSlug: "ps4-fat",
      slug: "ps4-fat-blue",
      colorPt: "Azul Wave",
      colorEn: "Wave Blue",
      releaseDate: new Date("2015-06-01"),
      limitedEdition: true,
      editionName: "Limited Edition Blue",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps4-blue.webp",
    },
    {
      variantSlug: "ps4-fat",
      slug: "ps4-fat-500m",
      colorPt: "500 Million Limited",
      colorEn: "500 Million Limited",
      releaseDate: new Date("2018-08-24"),
      limitedEdition: true,
      editionName: "500 Million Edition",
      material: "Plástico translúcido",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps4-500m.webp",
    },

    // ========================
    // PlayStation 4 (Slim)
    // ========================
    {
      variantSlug: "ps4-slim",
      slug: "ps4-slim-black",
      colorPt: "Preto Fosco",
      colorEn: "Matte Black",
      releaseDate: new Date("2016-09-15"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps4-slim-black.webp",
    },
    {
      variantSlug: "ps4-slim",
      slug: "ps4-slim-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("2017-01-01"),
      limitedEdition: true,
      editionName: "Golden Limited",
      material: "Plástico ABS com revestimento metálico",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps4-gold.webp",
    },
    {
      variantSlug: "ps4-slim",
      slug: "ps4-slim-uncharted",
      colorPt: "Uncharted 4",
      colorEn: "Uncharted 4",
      releaseDate: new Date("2017-03-01"),
      limitedEdition: true,
      editionName: "Uncharted 4 Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps4-uncharted.webp",
    },
    {
      variantSlug: "ps4-slim",
      slug: "ps4-slim-rose-gold",
      colorPt: "Rosa Dourado",
      colorEn: "Rose Gold",
      releaseDate: new Date("2018-02-01"),
      limitedEdition: true,
      editionName: "Rose Gold Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps4-rose-gold.webp",
    },

    // ========================
    // PlayStation 4 (Pro)
    // ========================
    {
      variantSlug: "ps4-pro",
      slug: "ps4-pro-black",
      colorPt: "Preto Fosco",
      colorEn: "Matte Black",
      releaseDate: new Date("2016-11-10"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps4-pro-black.webp",
    },
    {
      variantSlug: "ps4-pro",
      slug: "ps4-pro-god-of-war",
      colorPt: "God of War",
      colorEn: "God of War",
      releaseDate: new Date("2018-04-20"),
      limitedEdition: true,
      editionName: "God of War Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps4-pro-gow.webp",
    },
    {
      variantSlug: "ps4-pro",
      slug: "ps4-pro-500m",
      colorPt: "500 Million Pro",
      colorEn: "500 Million Pro",
      releaseDate: new Date("2018-08-24"),
      limitedEdition: true,
      editionName: "500 Million Edition",
      material: "Plástico translúcido",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps4-pro-500m.webp",
    },
    {
      variantSlug: "ps4-pro",
      slug: "ps4-pro-death-stranding",
      colorPt: "Death Stranding",
      colorEn: "Death Stranding",
      releaseDate: new Date("2019-11-08"),
      limitedEdition: true,
      editionName: "Death Stranding Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps4-pro-death-stranding.webp",
    },

    // ========================
    // PlayStation 5 (Standard)
    // ========================
    {
      variantSlug: "ps5-standard",
      slug: "ps5-standard-white-black",
      colorPt: "Branco e Preto",
      colorEn: "White and Black",
      releaseDate: new Date("2020-11-12"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco e Brilhante",
      imageUrl: "images/skins/sony/ps5-standard.webp",
    },
    {
      variantSlug: "ps5-standard",
      slug: "ps5-standard-cosmic-red",
      colorPt: "Vermelho Cósmico",
      colorEn: "Cosmic Red",
      releaseDate: new Date("2021-06-11"),
      limitedEdition: true,
      editionName: "Cosmic Red",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps5-red.webp",
    },
    {
      variantSlug: "ps5-standard",
      slug: "ps5-standard-god-of-war",
      colorPt: "God of War Ragnarök",
      colorEn: "God of War Ragnarök",
      releaseDate: new Date("2022-11-09"),
      limitedEdition: true,
      editionName: "God of War Ragnarök Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps5-gow.webp",
    },
    {
      variantSlug: "ps5-standard",
      slug: "ps5-standard-spider-man",
      colorPt: "Spider-Man 2",
      colorEn: "Spider-Man 2",
      releaseDate: new Date("2023-10-20"),
      limitedEdition: true,
      editionName: "Spider-Man 2 Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps5-spiderman.webp",
    },

    // ========================
    // PlayStation 5 (Digital)
    // ========================
    {
      variantSlug: "ps5-digital",
      slug: "ps5-digital-white-black",
      colorPt: "Branco e Preto",
      colorEn: "White and Black",
      releaseDate: new Date("2020-11-12"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco e Brilhante",
      imageUrl: "images/skins/sony/ps5-digital.webp",
    },
    {
      variantSlug: "ps5-digital",
      slug: "ps5-digital-nova-pink",
      colorPt: "Rosa Nova",
      colorEn: "Nova Pink",
      releaseDate: new Date("2022-01-14"),
      limitedEdition: true,
      editionName: "Nova Pink",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps5-pink.webp",
    },
    {
      variantSlug: "ps5-digital",
      slug: "ps5-digital-purple",
      colorPt: "Roxo Profundo",
      colorEn: "Deep Purple",
      releaseDate: new Date("2022-09-15"),
      limitedEdition: true,
      editionName: "Deep Purple",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps5-purple.webp",
    },
    {
      variantSlug: "ps5-digital",
      slug: "ps5-digital-blue",
      colorPt: "Azul Cobalto",
      colorEn: "Cobalt Blue",
      releaseDate: new Date("2022-09-15"),
      limitedEdition: true,
      editionName: "Cobalt Blue",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps5-blue.webp",
    },

    // ========================
    // PlayStation 5 (Slim)
    // ========================
    {
      variantSlug: "ps5-slim",
      slug: "ps5-slim-white-black",
      colorPt: "Branco e Preto",
      colorEn: "White and Black",
      releaseDate: new Date("2023-11-10"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco e Brilhante",
      imageUrl: "images/skins/sony/ps5-slim.webp",
    },
    {
      variantSlug: "ps5-slim",
      slug: "ps5-slim-volcanic-red",
      colorPt: "Vermelho Vulcânico",
      colorEn: "Volcanic Red",
      releaseDate: new Date("2024-02-01"),
      limitedEdition: true,
      editionName: "Volcanic Red",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps5-slim-red.webp",
    },
    {
      variantSlug: "ps5-slim",
      slug: "ps5-slim-satin-silver",
      colorPt: "Prata Cetim",
      colorEn: "Satin Silver",
      releaseDate: new Date("2024-02-01"),
      limitedEdition: true,
      editionName: "Satin Silver",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sony/ps5-slim-silver.webp",
    },

    // ========================
    // PlayStation 5 (Pro)
    // ========================
    {
      variantSlug: "ps5-pro",
      slug: "ps5-pro-black",
      colorPt: "Preto Profundo",
      colorEn: "Deep Black",
      releaseDate: new Date("2024-11-10"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sony/ps5-pro-black.webp",
    },
    {
      variantSlug: "ps5-pro",
      slug: "ps5-pro-gold-trim",
      colorPt: "Preto com Dourado",
      colorEn: "Black with Gold Trim",
      releaseDate: new Date("2024-11-10"),
      limitedEdition: true,
      editionName: "Premium Edition",
      material: "Plástico ABS",
      finish: "Fosco com detalhes brilhantes",
      imageUrl: "images/skins/sony/ps5-pro-gold.webp",
    },

    // ========================
    // Xbox Original
    // ========================
    {
      variantSlug: "xbox-fat",
      slug: "xbox-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2001-11-15"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox-black.webp",
    },
    {
      variantSlug: "xbox-fat",
      slug: "xbox-crystal",
      colorPt: "Cristal",
      colorEn: "Crystal",
      releaseDate: new Date("2003-11-01"),
      limitedEdition: true,
      editionName: "Crystal Edition",
      material: "Plástico translúcido",
      finish: "Brilhante",
      imageUrl: "images/skins/microsoft/xbox-crystal.webp",
    },
    {
      variantSlug: "xbox-fat",
      slug: "xbox-halo-green",
      colorPt: "Verde Halo",
      colorEn: "Halo Green",
      releaseDate: new Date("2004-11-09"),
      limitedEdition: true,
      editionName: "Halo 2 Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox-halo2.webp",
    },

    // ========================
    // Xbox 360 (Fat)
    // ========================
    {
      variantSlug: "xbox360-fat",
      slug: "xbox360-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2005-11-22"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/microsoft/xbox360-white.webp",
    },
    {
      variantSlug: "xbox360-fat",
      slug: "xbox360-elite",
      colorPt: "Preto Elite",
      colorEn: "Elite Black",
      releaseDate: new Date("2007-04-29"),
      limitedEdition: true,
      editionName: "Elite Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360-elite.webp",
    },
    {
      variantSlug: "xbox360-fat",
      slug: "xbox360-halo3",
      colorPt: "Halo 3 Edition",
      colorEn: "Halo 3 Edition",
      releaseDate: new Date("2007-09-25"),
      limitedEdition: true,
      editionName: "Halo 3 Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360-halo3.webp",
    },
    {
      variantSlug: "xbox360-fat",
      slug: "xbox360-red-ring",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("2008-10-01"),
      limitedEdition: true,
      editionName: "Red Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/microsoft/xbox360-red.webp",
    },

    // ========================
    // Xbox 360 (Slim)
    // ========================
    {
      variantSlug: "xbox360-slim",
      slug: "xbox360s-black",
      colorPt: "Preto Fosco",
      colorEn: "Matte Black",
      releaseDate: new Date("2010-06-14"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360s-black.webp",
    },
    {
      variantSlug: "xbox360-slim",
      slug: "xbox360s-halo4",
      colorPt: "Halo 4 Edition",
      colorEn: "Halo 4 Edition",
      releaseDate: new Date("2012-11-06"),
      limitedEdition: true,
      editionName: "Halo 4 Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360-halo4.webp",
    },
    {
      variantSlug: "xbox360-slim",
      slug: "xbox360s-glow",
      colorPt: "Brilho Azul",
      colorEn: "Glow Blue",
      releaseDate: new Date("2011-10-01"),
      limitedEdition: true,
      editionName: "Glow Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/microsoft/xbox360-glow.webp",
    },
    {
      variantSlug: "xbox360-slim",
      slug: "xbox360s-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("2013-01-01"),
      limitedEdition: true,
      editionName: "Gold Limited",
      material: "Plástico ABS com revestimento metálico",
      finish: "Brilhante",
      imageUrl: "images/skins/microsoft/xbox360-gold.webp",
    },

    // ========================
    // Xbox 360 (E)
    // ========================
    {
      variantSlug: "xbox360-e",
      slug: "xbox360e-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2013-06-10"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360e-black.webp",
    },
    {
      variantSlug: "xbox360-e",
      slug: "xbox360e-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2013-09-01"),
      limitedEdition: true,
      editionName: "White Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360e-white.webp",
    },

    // ========================
    // Xbox One (Fat)
    // ========================
    {
      variantSlug: "xboxone-fat",
      slug: "xboxone-black",
      colorPt: "Preto Fosco",
      colorEn: "Matte Black",
      releaseDate: new Date("2013-11-22"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxone-black.webp",
    },
    {
      variantSlug: "xboxone-fat",
      slug: "xboxone-sunset",
      colorPt: "Pôr do Sol",
      colorEn: "Sunset Overdrive",
      releaseDate: new Date("2014-10-28"),
      limitedEdition: true,
      editionName: "Sunset Overdrive Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxone-sunset.webp",
    },
    {
      variantSlug: "xboxone-fat",
      slug: "xboxone-mcfarlane",
      colorPt: "Edição McFarlane",
      colorEn: "McFarlane Edition",
      releaseDate: new Date("2015-02-20"),
      limitedEdition: true,
      editionName: "Advanced Warfare Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxone-mcfarlane.webp",
    },

    // ========================
    // Xbox One S
    // ========================
    {
      variantSlug: "xboxone-s",
      slug: "xboxones-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2016-08-02"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxones-white.webp",
    },
    {
      variantSlug: "xboxone-s",
      slug: "xboxones-battlefield",
      colorPt: "Battlefield 1",
      colorEn: "Battlefield 1",
      releaseDate: new Date("2016-10-21"),
      limitedEdition: true,
      editionName: "Battlefield 1 Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxones-bf1.webp",
    },
    {
      variantSlug: "xboxone-s",
      slug: "xboxones-gears",
      colorPt: "Gears of War 4",
      colorEn: "Gears of War 4",
      releaseDate: new Date("2016-10-11"),
      limitedEdition: true,
      editionName: "Gears of War 4 Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxones-gears.webp",
    },
    {
      variantSlug: "xboxone-s",
      slug: "xboxones-project-scorpio",
      colorPt: "Projeto Scorpio",
      colorEn: "Project Scorpio",
      releaseDate: new Date("2017-11-07"),
      limitedEdition: true,
      editionName: "Project Scorpio Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxones-scorpio.webp",
    },

    // ========================
    // Xbox One X
    // ========================
    {
      variantSlug: "xboxone-x",
      slug: "xboxonex-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2017-11-07"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxonex-black.webp",
    },
    {
      variantSlug: "xboxone-x",
      slug: "xboxonex-cyberpunk",
      colorPt: "Cyberpunk 2077",
      colorEn: "Cyberpunk 2077",
      releaseDate: new Date("2020-06-01"),
      limitedEdition: true,
      editionName: "Cyberpunk 2077 Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxonex-cyberpunk.webp",
    },
    {
      variantSlug: "xboxone-x",
      slug: "xboxonex-fallout",
      colorPt: "Fallout 76",
      colorEn: "Fallout 76",
      releaseDate: new Date("2018-11-14"),
      limitedEdition: true,
      editionName: "Fallout 76 Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxonex-fallout.webp",
    },

    // ========================
    // Xbox Series X
    // ========================
    {
      variantSlug: "xboxseriesx-standard",
      slug: "xboxsx-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2020-11-10"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxsx-black.webp",
    },
    {
      variantSlug: "xboxseriesx-standard",
      slug: "xboxsx-halo-infinite",
      colorPt: "Halo Infinite",
      colorEn: "Halo Infinite",
      releaseDate: new Date("2021-11-15"),
      limitedEdition: true,
      editionName: "Halo Infinite Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxsx-halo.webp",
    },
    {
      variantSlug: "xboxseriesx-standard",
      slug: "xboxsx-forza",
      colorPt: "Forza Horizon 5",
      colorEn: "Forza Horizon 5",
      releaseDate: new Date("2021-11-05"),
      limitedEdition: true,
      editionName: "Forza Horizon 5 Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxsx-forza.webp",
    },
    {
      variantSlug: "xboxseriesx-standard",
      slug: "xboxsx-stellar-shift",
      colorPt: "Deslocamento Estelar",
      colorEn: "Stellar Shift",
      releaseDate: new Date("2023-03-01"),
      limitedEdition: true,
      editionName: "Stellar Shift Special Edition",
      material: "Plástico ABS",
      finish: "Gradiente",
      imageUrl: "images/skins/microsoft/xboxsx-stellar.webp",
    },

    // ========================
    // Xbox Series S
    // ========================
    {
      variantSlug: "xboxseriess-standard",
      slug: "xboxss-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2020-11-10"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxss-white.webp",
    },
    {
      variantSlug: "xboxseriess-standard",
      slug: "xboxss-carbon-black",
      colorPt: "Preto Carbono",
      colorEn: "Carbon Black",
      releaseDate: new Date("2023-09-01"),
      limitedEdition: true,
      editionName: "Carbon Black Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxss-black.webp",
    },
    {
      variantSlug: "xboxseriess-standard",
      slug: "xboxss-volt-green",
      colorPt: "Verde Volts",
      colorEn: "Volt Green",
      releaseDate: new Date("2021-11-15"),
      limitedEdition: true,
      editionName: "Electric Volt",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxss-green.webp",
    },
    {
      variantSlug: "xboxseriess-standard",
      slug: "xboxss-robot-white",
      colorPt: "Branco Robótico",
      colorEn: "Robot White",
      releaseDate: new Date("2022-08-30"),
      limitedEdition: true,
      editionName: "Robot White Special",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxss-robot.webp",
    },

    // ========================
    // Edições Especiais e Limitadas Adicionais
    // ========================

    // Xbox 360 - Edições Raras
    {
      variantSlug: "xbox360-fat",
      slug: "xbox360-star-wars",
      colorPt: "Star Wars",
      colorEn: "Star Wars",
      releaseDate: new Date("2012-10-30"),
      limitedEdition: true,
      editionName: "Star Wars Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360-starwars.webp",
    },
    {
      variantSlug: "xbox360-slim",
      slug: "xbox360s-call-of-duty",
      colorPt: "Call of Duty",
      colorEn: "Call of Duty",
      releaseDate: new Date("2011-11-08"),
      limitedEdition: true,
      editionName: "Modern Warfare 3 Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xbox360-cod.webp",
    },

    // Xbox One - Edições Especiais
    {
      variantSlug: "xboxone-s",
      slug: "xboxones-sea-of-thieves",
      colorPt: "Sea of Thieves",
      colorEn: "Sea of Thieves",
      releaseDate: new Date("2018-03-20"),
      limitedEdition: true,
      editionName: "Sea of Thieves Limited",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxones-sea.webp",
    },
    {
      variantSlug: "xboxone-x",
      slug: "xboxonex-taco-bell",
      colorPt: "Taco Bell",
      colorEn: "Taco Bell",
      releaseDate: new Date("2019-11-01"),
      limitedEdition: true,
      editionName: "Taco Bell Contest Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/microsoft/xboxonex-tacobell.webp",
    },

    // Xbox Series X|S - Edições Atuais
    {
      variantSlug: "xboxseriesx-standard",
      slug: "xboxsx-diablo",
      colorPt: "Diablo IV",
      colorEn: "Diablo IV",
      releaseDate: new Date("2023-05-15"),
      limitedEdition: true,
      editionName: "Diablo IV Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxsx-diablo.webp",
    },
    {
      variantSlug: "xboxseriess-standard",
      slug: "xboxss-golden-ridge",
      colorPt: "Crista Dourada",
      colorEn: "Golden Ridge",
      releaseDate: new Date("2023-11-01"),
      limitedEdition: true,
      editionName: "Golden Ridge Special",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/microsoft/xboxss-golden.webp",
    },

    // ========================
    // Nintendo Entertainment System (NES)
    // ========================
    {
      variantSlug: "nes-front-loader",
      slug: "nes-front-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("1985-07-15"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/nes-gray.webp",
    },
    {
      variantSlug: "nes-front-loader",
      slug: "nes-front-famicom",
      colorPt: "Famicom Vermelho",
      colorEn: "Famicom Red",
      releaseDate: new Date("1983-07-15"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/famicom-red.webp",
    },
    {
      variantSlug: "nes-top-loader",
      slug: "nes-top-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("1993-06-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/nes-top-gray.webp",
    },

    // ========================
    // Game Boy (Original)
    // ========================
    {
      variantSlug: "gameboy-original",
      slug: "gb-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("1989-04-21"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/gb-gray.webp",
    },
    {
      variantSlug: "gameboy-original",
      slug: "gb-play-it-loud-black",
      colorPt: "Preto Play It Loud",
      colorEn: "Play It Loud Black",
      releaseDate: new Date("1995-03-01"),
      limitedEdition: true,
      editionName: "Play It Loud Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gb-black.webp",
    },
    {
      variantSlug: "gameboy-original",
      slug: "gb-play-it-loud-red",
      colorPt: "Vermelho Play It Loud",
      colorEn: "Play It Loud Red",
      releaseDate: new Date("1995-03-01"),
      limitedEdition: true,
      editionName: "Play It Loud Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gb-red.webp",
    },
    {
      variantSlug: "gameboy-original",
      slug: "gb-play-it-loud-yellow",
      colorPt: "Amarelo Play It Loud",
      colorEn: "Play It Loud Yellow",
      releaseDate: new Date("1995-03-01"),
      limitedEdition: true,
      editionName: "Play It Loud Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gb-yellow.webp",
    },
    {
      variantSlug: "gameboy-original",
      slug: "gb-play-it-loud-green",
      colorPt: "Verde Play It Loud",
      colorEn: "Play It Loud Green",
      releaseDate: new Date("1995-03-01"),
      limitedEdition: true,
      editionName: "Play It Loud Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gb-green.webp",
    },
    {
      variantSlug: "gameboy-original",
      slug: "gb-play-it-loud-blue",
      colorPt: "Azul Play It Loud",
      colorEn: "Play It Loud Blue",
      releaseDate: new Date("1995-03-01"),
      limitedEdition: true,
      editionName: "Play It Loud Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gb-blue.webp",
    },
    {
      variantSlug: "gameboy-original",
      slug: "gb-play-it-loud-clear",
      colorPt: "Transparente Play It Loud",
      colorEn: "Play It Loud Clear",
      releaseDate: new Date("1995-03-01"),
      limitedEdition: true,
      editionName: "Play It Loud Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gb-clear.webp",
    },

    // ========================
    // Game Boy Pocket
    // ========================
    {
      variantSlug: "gameboy-pocket",
      slug: "gb-pocket-silver",
      colorPt: "Prata",
      colorEn: "Silver",
      releaseDate: new Date("1996-07-21"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/gbp-silver.webp",
    },
    {
      variantSlug: "gameboy-pocket",
      slug: "gb-pocket-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("1996-12-01"),
      limitedEdition: true,
      editionName: "Red Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbp-red.webp",
    },
    {
      variantSlug: "gameboy-pocket",
      slug: "gb-pocket-yellow",
      colorPt: "Amarelo",
      colorEn: "Yellow",
      releaseDate: new Date("1996-12-01"),
      limitedEdition: true,
      editionName: "Yellow Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbp-yellow.webp",
    },
    {
      variantSlug: "gameboy-pocket",
      slug: "gb-pocket-green",
      colorPt: "Verde",
      colorEn: "Green",
      releaseDate: new Date("1996-12-01"),
      limitedEdition: true,
      editionName: "Green Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbp-green.webp",
    },
    {
      variantSlug: "gameboy-pocket",
      slug: "gb-pocket-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("1996-12-01"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbp-blue.webp",
    },

    // ========================
    // Game Boy Color
    // ========================
    {
      variantSlug: "gameboy-color",
      slug: "gbc-purple",
      colorPt: "Roxo",
      colorEn: "Purple",
      releaseDate: new Date("1998-10-21"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-purple.webp",
    },
    {
      variantSlug: "gameboy-color",
      slug: "gbc-teal",
      colorPt: "Verde-azulado",
      colorEn: "Teal",
      releaseDate: new Date("1998-10-21"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-teal.webp",
    },
    {
      variantSlug: "gameboy-color",
      slug: "gbc-yellow",
      colorPt: "Amarelo",
      colorEn: "Yellow",
      releaseDate: new Date("1998-11-01"),
      limitedEdition: true,
      editionName: "Pokémon Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-yellow.webp",
    },
    {
      variantSlug: "gameboy-color",
      slug: "gbc-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("1999-01-01"),
      limitedEdition: true,
      editionName: "Red Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-red.webp",
    },
    {
      variantSlug: "gameboy-color",
      slug: "gbc-green",
      colorPt: "Verde",
      colorEn: "Green",
      releaseDate: new Date("1999-01-01"),
      limitedEdition: true,
      editionName: "Green Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-green.webp",
    },
    {
      variantSlug: "gameboy-color",
      slug: "gbc-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("1999-01-01"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-blue.webp",
    },
    {
      variantSlug: "gameboy-color",
      slug: "gbc-pink",
      colorPt: "Rosa",
      colorEn: "Pink",
      releaseDate: new Date("1999-01-01"),
      limitedEdition: true,
      editionName: "Pink Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-pink.webp",
    },
    {
      variantSlug: "gameboy-color",
      slug: "gbc-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("1999-11-01"),
      limitedEdition: true,
      editionName: "Zelda Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gbc-gold.webp",
    },

    // ========================
    // Super Nintendo (SNES)
    // ========================
    {
      variantSlug: "snes-original",
      slug: "snes-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("1990-08-23"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/snes-gray.webp",
    },
    {
      variantSlug: "snes-original",
      slug: "snes-super-famicom",
      colorPt: "Super Famicom",
      colorEn: "Super Famicom",
      releaseDate: new Date("1990-11-21"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/super-famicom.webp",
    },

    // ========================
    // Nintendo 64
    // ========================
    {
      variantSlug: "n64-standard",
      slug: "n64-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("1996-09-29"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/n64-gray.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1997-01-01"),
      limitedEdition: true,
      editionName: "Funtastic Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-black.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-green",
      colorPt: "Verde",
      colorEn: "Green",
      releaseDate: new Date("1997-11-01"),
      limitedEdition: true,
      editionName: "Funtastic Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-green.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("1997-11-01"),
      limitedEdition: true,
      editionName: "Funtastic Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-blue.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("1997-11-01"),
      limitedEdition: true,
      editionName: "Funtastic Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-red.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-yellow",
      colorPt: "Amarelo",
      colorEn: "Yellow",
      releaseDate: new Date("1998-03-01"),
      limitedEdition: true,
      editionName: "Funtastic Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-yellow.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-orange",
      colorPt: "Laranja",
      colorEn: "Orange",
      releaseDate: new Date("1998-03-01"),
      limitedEdition: true,
      editionName: "Funtastic Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-orange.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-purple",
      colorPt: "Roxo",
      colorEn: "Purple",
      releaseDate: new Date("1999-05-01"),
      limitedEdition: true,
      editionName: "Funtastic Series",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-purple.webp",
    },
    {
      variantSlug: "n64-standard",
      slug: "n64-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("1998-11-01"),
      limitedEdition: true,
      editionName: "Zelda Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/n64-gold.webp",
    },

    // ========================
    // GameCube
    // ========================
    {
      variantSlug: "gamecube-standard",
      slug: "gc-purple",
      colorPt: "Roxo",
      colorEn: "Purple",
      releaseDate: new Date("2001-09-14"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gc-purple.webp",
    },
    {
      variantSlug: "gamecube-standard",
      slug: "gc-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2002-05-01"),
      limitedEdition: true,
      editionName: "Special Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gc-black.webp",
    },
    {
      variantSlug: "gamecube-standard",
      slug: "gc-orange",
      colorPt: "Laranja",
      colorEn: "Orange",
      releaseDate: new Date("2002-11-01"),
      limitedEdition: true,
      editionName: "Spice Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gc-orange.webp",
    },
    {
      variantSlug: "gamecube-standard",
      slug: "gc-silver",
      colorPt: "Prata",
      colorEn: "Silver",
      releaseDate: new Date("2003-01-01"),
      limitedEdition: true,
      editionName: "Platinum Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gc-silver.webp",
    },
    {
      variantSlug: "gamecube-standard",
      slug: "gc-gold",
      colorPt: "Dourado Zelda",
      colorEn: "Zelda Gold",
      releaseDate: new Date("2003-03-24"),
      limitedEdition: true,
      editionName: "Zelda Bundle",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/gc-gold.webp",
    },

    // ========================
    // Nintendo DS
    // ========================
    {
      variantSlug: "ds-original",
      slug: "ds-silver",
      colorPt: "Prata",
      colorEn: "Silver",
      releaseDate: new Date("2004-11-21"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/ds-silver.webp",
    },
    {
      variantSlug: "ds-original",
      slug: "ds-pink",
      colorPt: "Rosa",
      colorEn: "Pink",
      releaseDate: new Date("2005-03-24"),
      limitedEdition: true,
      editionName: "Pink Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/ds-pink.webp",
    },
    {
      variantSlug: "ds-original",
      slug: "ds-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("2005-03-24"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/ds-blue.webp",
    },

    // DS Lite
    {
      variantSlug: "ds-lite",
      slug: "ds-lite-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2006-03-02"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/dsl-white.webp",
    },
    {
      variantSlug: "ds-lite",
      slug: "ds-lite-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2006-06-11"),
      limitedEdition: true,
      editionName: "Black Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/dsl-black.webp",
    },
    {
      variantSlug: "ds-lite",
      slug: "ds-lite-pink",
      colorPt: "Rosa",
      colorEn: "Pink",
      releaseDate: new Date("2006-09-02"),
      limitedEdition: true,
      editionName: "Pink Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/dsl-pink.webp",
    },
    {
      variantSlug: "ds-lite",
      slug: "ds-lite-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("2006-10-01"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/dsl-blue.webp",
    },
    {
      variantSlug: "ds-lite",
      slug: "ds-lite-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("2007-01-01"),
      limitedEdition: true,
      editionName: "Red Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/dsl-red.webp",
    },
    {
      variantSlug: "ds-lite",
      slug: "ds-lite-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("2007-06-03"),
      limitedEdition: true,
      editionName: "Zelda Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/dsl-gold.webp",
    },

    // ========================
    // Wii
    // ========================
    {
      variantSlug: "wii-original",
      slug: "wii-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2006-11-19"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/wii-white.webp",
    },
    {
      variantSlug: "wii-original",
      slug: "wii-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2009-08-01"),
      limitedEdition: true,
      editionName: "Black Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/wii-black.webp",
    },
    {
      variantSlug: "wii-original",
      slug: "wii-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("2010-11-07"),
      limitedEdition: true,
      editionName: "Mario Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/wii-red.webp",
    },
    {
      variantSlug: "wii-original",
      slug: "wii-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("2011-11-06"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/wii-blue.webp",
    },

    // ========================
    // Nintendo 3DS
    // ========================
    // 3DS Original
    {
      variantSlug: "3ds-original",
      slug: "3ds-aqua",
      colorPt: "Verde-azulado",
      colorEn: "Aqua Blue",
      releaseDate: new Date("2011-02-26"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/3ds-aqua.webp",
    },
    {
      variantSlug: "3ds-original",
      slug: "3ds-cosmo",
      colorPt: "Preto Cósmico",
      colorEn: "Cosmo Black",
      releaseDate: new Date("2011-02-26"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/3ds-black.webp",
    },
    {
      variantSlug: "3ds-original",
      slug: "3ds-flame",
      colorPt: "Vermelho Flamejante",
      colorEn: "Flame Red",
      releaseDate: new Date("2011-08-01"),
      limitedEdition: true,
      editionName: "Red Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/3ds-red.webp",
    },

    // 3DS XL
    {
      variantSlug: "3ds-xl",
      slug: "3ds-xl-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("2012-07-28"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/3ds-xl-blue.webp",
    },
    {
      variantSlug: "3ds-xl",
      slug: "3ds-xl-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("2012-07-28"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/3ds-xl-red.webp",
    },
    {
      variantSlug: "3ds-xl",
      slug: "3ds-xl-pink",
      colorPt: "Rosa",
      colorEn: "Pink",
      releaseDate: new Date("2013-01-01"),
      limitedEdition: true,
      editionName: "Pink Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/3ds-xl-pink.webp",
    },
    {
      variantSlug: "3ds-xl",
      slug: "3ds-xl-gold",
      colorPt: "Dourado Zelda",
      colorEn: "Zelda Gold",
      releaseDate: new Date("2013-11-22"),
      limitedEdition: true,
      editionName: "Zelda Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/3ds-xl-gold.webp",
    },

    // ========================
    // Wii U
    // ========================
    // Basic
    {
      variantSlug: "wiiu-basic",
      slug: "wiiu-basic-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2012-11-18"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/wiiu-basic-white.webp",
    },

    // Deluxe
    {
      variantSlug: "wiiu-deluxe",
      slug: "wiiu-deluxe-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2012-11-18"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/wiiu-deluxe-black.webp",
    },
    {
      variantSlug: "wiiu-deluxe",
      slug: "wiiu-deluxe-zelda",
      colorPt: "Zelda Wind Waker",
      colorEn: "Zelda Wind Waker",
      releaseDate: new Date("2013-09-20"),
      limitedEdition: true,
      editionName: "Zelda Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/nintendo/wiiu-zelda.webp",
    },

    // ========================
    // Nintendo Switch
    // ========================
    // Standard
    {
      variantSlug: "switch-standard",
      slug: "switch-neon",
      colorPt: "Neon",
      colorEn: "Neon",
      releaseDate: new Date("2017-03-03"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-neon.webp",
    },
    {
      variantSlug: "switch-standard",
      slug: "switch-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("2017-03-03"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-gray.webp",
    },
    {
      variantSlug: "switch-standard",
      slug: "switch-animal-crossing",
      colorPt: "Animal Crossing",
      colorEn: "Animal Crossing",
      releaseDate: new Date("2020-03-13"),
      limitedEdition: true,
      editionName: "Animal Crossing Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-ac.webp",
    },
    {
      variantSlug: "switch-standard",
      slug: "switch-mario-red",
      colorPt: "Vermelho Mario",
      colorEn: "Mario Red",
      releaseDate: new Date("2020-10-16"),
      limitedEdition: true,
      editionName: "Mario Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-mario-red.webp",
    },

    // OLED
    {
      variantSlug: "switch-oled",
      slug: "switch-oled-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("2021-10-08"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-oled-white.webp",
    },
    {
      variantSlug: "switch-oled",
      slug: "switch-oled-splatoon3",
      colorPt: "Splatoon 3",
      colorEn: "Splatoon 3",
      releaseDate: new Date("2022-08-26"),
      limitedEdition: true,
      editionName: "Splatoon 3 Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-oled-splatoon.webp",
    },
    {
      variantSlug: "switch-oled",
      slug: "switch-oled-zelda",
      colorPt: "Zelda Tears",
      colorEn: "Zelda Tears",
      releaseDate: new Date("2023-04-28"),
      limitedEdition: true,
      editionName: "Zelda Tears of the Kingdom",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-oled-zelda.webp",
    },

    // Lite
    {
      variantSlug: "switch-lite",
      slug: "switch-lite-turquoise",
      colorPt: "Turquesa",
      colorEn: "Turquoise",
      releaseDate: new Date("2019-09-20"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-lite-turquoise.webp",
    },
    {
      variantSlug: "switch-lite",
      slug: "switch-lite-coral",
      colorPt: "Coral",
      colorEn: "Coral",
      releaseDate: new Date("2020-04-03"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-lite-coral.webp",
    },
    {
      variantSlug: "switch-lite",
      slug: "switch-lite-yellow",
      colorPt: "Amarelo",
      colorEn: "Yellow",
      releaseDate: new Date("2019-09-20"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-lite-yellow.webp",
    },
    {
      variantSlug: "switch-lite",
      slug: "switch-lite-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("2019-09-20"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-lite-gray.webp",
    },
    {
      variantSlug: "switch-lite",
      slug: "switch-lite-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("2021-05-21"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-lite-blue.webp",
    },
    {
      variantSlug: "switch-lite",
      slug: "switch-lite-pink",
      colorPt: "Rosa",
      colorEn: "Pink",
      releaseDate: new Date("2021-05-21"),
      limitedEdition: true,
      editionName: "Pink Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-lite-pink.webp",
    },
    {
      variantSlug: "switch-lite",
      slug: "switch-lite-pokemon",
      colorPt: "Pokémon",
      colorEn: "Pokémon",
      releaseDate: new Date("2021-11-05"),
      limitedEdition: true,
      editionName: "Pokémon Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/nintendo/switch-lite-pokemon.webp",
    },

    // ========================
    // Sega Master System
    // ========================
    // Modelo Original
    {
      variantSlug: "mastersystem-original",
      slug: "mastersystem-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1985-10-20"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/mastersystem-black.webp",
    },
    {
      variantSlug: "mastersystem-original",
      slug: "mastersystem-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("1986-09-01"),
      limitedEdition: true,
      editionName: "Gold Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/mastersystem-gold.webp",
    },

    // Master System II
    {
      variantSlug: "mastersystem-ii",
      slug: "mastersystem2-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("1990-01-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/mastersystem2-white.webp",
    },
    {
      variantSlug: "mastersystem-ii",
      slug: "mastersystem2-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("1991-06-01"),
      limitedEdition: true,
      editionName: "Red Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/mastersystem2-red.webp",
    },
    {
      variantSlug: "mastersystem-ii",
      slug: "mastersystem2-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("1991-06-01"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/mastersystem2-blue.webp",
    },

    // ========================
    // Sega Mega Drive/Genesis
    // ========================
    // Modelo 1
    {
      variantSlug: "megadrive-model1",
      slug: "megadrive1-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1988-10-29"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/megadrive1-black.webp",
    },
    {
      variantSlug: "megadrive-model1",
      slug: "megadrive1-altered-beast",
      colorPt: "Altered Beast",
      colorEn: "Altered Beast",
      releaseDate: new Date("1989-08-14"),
      limitedEdition: true,
      editionName: "Altered Beast Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/megadrive-alteredbeast.webp",
    },

    // Modelo 2
    {
      variantSlug: "megadrive-model2",
      slug: "megadrive2-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1993-01-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/megadrive2-black.webp",
    },
    {
      variantSlug: "megadrive-model2",
      slug: "megadrive2-sonic2",
      colorPt: "Sonic 2",
      colorEn: "Sonic 2",
      releaseDate: new Date("1992-11-24"),
      limitedEdition: true,
      editionName: "Sonic 2 Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/megadrive-sonic2.webp",
    },
    {
      variantSlug: "megadrive-model2",
      slug: "megadrive2-sports",
      colorPt: "Sports",
      colorEn: "Sports",
      releaseDate: new Date("1994-03-01"),
      limitedEdition: true,
      editionName: "Sports Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/megadrive-sports.webp",
    },

    // Edições especiais
    {
      variantSlug: "megadrive-model2",
      slug: "megadrive2-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("1994-11-01"),
      limitedEdition: true,
      editionName: "Golden Edition",
      material: "Plástico ABS com revestimento",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/megadrive-gold.webp",
    },
    {
      variantSlug: "megadrive-model2",
      slug: "megadrive2-sonic",
      colorPt: "Sonic The Hedgehog",
      colorEn: "Sonic The Hedgehog",
      releaseDate: new Date("1993-12-01"),
      limitedEdition: true,
      editionName: "Sonic Special",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/megadrive-sonic.webp",
    },

    // ========================
    // Sega Saturn
    // ========================
    // Modelo 1
    {
      variantSlug: "saturn-model1",
      slug: "saturn1-gray",
      colorPt: "Cinza",
      colorEn: "Gray",
      releaseDate: new Date("1994-11-22"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/saturn1-gray.webp",
    },
    {
      variantSlug: "saturn-model1",
      slug: "saturn1-virtua-fighter",
      colorPt: "Virtua Fighter",
      colorEn: "Virtua Fighter",
      releaseDate: new Date("1995-05-01"),
      limitedEdition: true,
      editionName: "Virtua Fighter Bundle",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/saturn-virtuafighter.webp",
    },

    // Modelo 2
    {
      variantSlug: "saturn-model2",
      slug: "saturn2-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("1996-01-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/saturn2-white.webp",
    },
    {
      variantSlug: "saturn-model2",
      slug: "saturn2-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1996-06-01"),
      limitedEdition: true,
      editionName: "Black Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/saturn2-black.webp",
    },
    {
      variantSlug: "saturn-model2",
      slug: "saturn2-nights",
      colorPt: "Nights into Dreams",
      colorEn: "Nights into Dreams",
      releaseDate: new Date("1996-07-05"),
      limitedEdition: true,
      editionName: "Nights Bundle",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/saturn-nights.webp",
    },

    // Edições japonesas
    {
      variantSlug: "saturn-model2",
      slug: "saturn2-vampire",
      colorPt: "Vampire Savior",
      colorEn: "Vampire Savior",
      releaseDate: new Date("1997-05-01"),
      limitedEdition: true,
      editionName: "Vampire Savior Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/saturn-vampire.webp",
    },

    // ========================
    // Sega Dreamcast
    // ========================
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-white",
      colorPt: "Branco",
      colorEn: "White",
      releaseDate: new Date("1999-11-27"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-white.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("2000-09-09"),
      limitedEdition: true,
      editionName: "Black Sports Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-black.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("2000-12-01"),
      limitedEdition: true,
      editionName: "Sega Sports Blue",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-blue.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("2000-12-01"),
      limitedEdition: true,
      editionName: "Sega Sports Red",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-red.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-yellow",
      colorPt: "Amarelo",
      colorEn: "Yellow",
      releaseDate: new Date("2000-12-01"),
      limitedEdition: true,
      editionName: "Hello Kitty Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-yellow.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-green",
      colorPt: "Verde",
      colorEn: "Green",
      releaseDate: new Date("2001-03-01"),
      limitedEdition: true,
      editionName: "Sakura Taisen Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-green.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-sonic",
      colorPt: "Sonic Adventure",
      colorEn: "Sonic Adventure",
      releaseDate: new Date("1999-12-23"),
      limitedEdition: true,
      editionName: "Sonic Adventure Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-sonic.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-seaman",
      colorPt: "Seaman",
      colorEn: "Seaman",
      releaseDate: new Date("2000-07-20"),
      limitedEdition: true,
      editionName: "Seaman Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-seaman.webp",
    },

    // Edições especiais
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-millennium",
      colorPt: "Edição do Milênio",
      colorEn: "Millennium Edition",
      releaseDate: new Date("2000-01-01"),
      limitedEdition: true,
      editionName: "Millennium Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-millennium.webp",
    },
    {
      variantSlug: "dreamcast-standard",
      slug: "dreamcast-transparent",
      colorPt: "Transparente",
      colorEn: "Clear",
      releaseDate: new Date("2000-09-01"),
      limitedEdition: true,
      editionName: "Clear Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/sega/dreamcast-clear.webp",
    },

    // ========================
    // Outros consoles Sega
    // ========================
    // Sega CD (Acessório, mas vamos considerar como skin do Mega Drive)
    {
      variantSlug: "megadrive-model2",
      slug: "segacd-black",
      colorPt: "Sega CD Preto",
      colorEn: "Sega CD Black",
      releaseDate: new Date("1992-12-12"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/segacd-black.webp",
    },

    // Sega 32X (Acessório)
    {
      variantSlug: "megadrive-model2",
      slug: "32x-black",
      colorPt: "32X Preto",
      colorEn: "32X Black",
      releaseDate: new Date("1994-12-03"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/sega/32x-black.webp",
    },

    // ========================
    // Atari 2600 (Heavy Sixer)
    // ========================
    {
      variantSlug: "atari2600-heavy-sixer",
      slug: "atari2600-heavy-woodgrain",
      colorPt: "Madeira",
      colorEn: "Woodgrain",
      releaseDate: new Date("1977-09-11"),
      limitedEdition: false,
      editionName: null,
      material: "Madeira plástica",
      finish: "Texturizado",
      imageUrl: "images/skins/atari/2600-heavy-woodgrain.webp",
    },
    {
      variantSlug: "atari2600-heavy-sixer",
      slug: "atari2600-heavy-all-black",
      colorPt: "Preto Total",
      colorEn: "All Black",
      releaseDate: new Date("1978-06-01"),
      limitedEdition: true,
      editionName: "Special Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/atari/2600-heavy-black.webp",
    },

    // ========================
    // Atari 2600 (Light Sixer)
    // ========================
    {
      variantSlug: "atari2600-light-sixer",
      slug: "atari2600-light-woodgrain",
      colorPt: "Madeira",
      colorEn: "Woodgrain",
      releaseDate: new Date("1978-01-01"),
      limitedEdition: false,
      editionName: null,
      material: "Madeira plástica",
      finish: "Texturizado",
      imageUrl: "images/skins/atari/2600-light-woodgrain.webp",
    },
    {
      variantSlug: "atari2600-light-sixer",
      slug: "atari2600-light-silver",
      colorPt: "Prata",
      colorEn: "Silver",
      releaseDate: new Date("1979-03-01"),
      limitedEdition: true,
      editionName: "Silver Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-light-silver.webp",
    },

    // ========================
    // Atari 2600 (4-Switch)
    // ========================
    {
      variantSlug: "atari2600-4-switch",
      slug: "atari2600-4switch-woodgrain",
      colorPt: "Madeira",
      colorEn: "Woodgrain",
      releaseDate: new Date("1980-01-01"),
      limitedEdition: false,
      editionName: null,
      material: "Madeira plástica",
      finish: "Texturizado",
      imageUrl: "images/skins/atari/2600-4switch-woodgrain.webp",
    },
    {
      variantSlug: "atari2600-4-switch",
      slug: "atari2600-4switch-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1982-01-01"),
      limitedEdition: true,
      editionName: "Darth Vader Edition",
      material: "Plástico ABS",
      finish: "Fosco",
      imageUrl: "images/skins/atari/2600-4switch-black.webp",
    },
    {
      variantSlug: "atari2600-4-switch",
      slug: "atari2600-4switch-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("1981-10-01"),
      limitedEdition: true,
      editionName: "Gold Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-4switch-gold.webp",
    },

    // ========================
    // Atari 2600 (Junior)
    // ========================
    {
      variantSlug: "atari2600-junior",
      slug: "atari2600-jr-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1986-01-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-jr-black.webp",
    },
    {
      variantSlug: "atari2600-junior",
      slug: "atari2600-jr-silver",
      colorPt: "Prata",
      colorEn: "Silver",
      releaseDate: new Date("1986-06-01"),
      limitedEdition: true,
      editionName: "Silver Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-jr-silver.webp",
    },
    {
      variantSlug: "atari2600-junior",
      slug: "atari2600-jr-red",
      colorPt: "Vermelho",
      colorEn: "Red",
      releaseDate: new Date("1987-01-01"),
      limitedEdition: true,
      editionName: "Red Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-jr-red.webp",
    },
    {
      variantSlug: "atari2600-junior",
      slug: "atari2600-jr-blue",
      colorPt: "Azul",
      colorEn: "Blue",
      releaseDate: new Date("1987-01-01"),
      limitedEdition: true,
      editionName: "Blue Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-jr-blue.webp",
    },

    // ========================
    // Atari 7800
    // ========================
    {
      variantSlug: "atari7800-standard",
      slug: "atari7800-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1986-05-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/7800-black.webp",
    },
    {
      variantSlug: "atari7800-standard",
      slug: "atari7800-silver",
      colorPt: "Prata",
      colorEn: "Silver",
      releaseDate: new Date("1987-01-01"),
      limitedEdition: true,
      editionName: "Silver Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/7800-silver.webp",
    },
    {
      variantSlug: "atari7800-standard",
      slug: "atari7800-gold",
      colorPt: "Dourado",
      colorEn: "Gold",
      releaseDate: new Date("1988-01-01"),
      limitedEdition: true,
      editionName: "Gold Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/7800-gold.webp",
    },

    // ========================
    // Edições Especiais e Promocionais
    // ========================

    // Atari 2600 Edições Temáticas
    {
      variantSlug: "atari2600-4-switch",
      slug: "atari2600-pacman",
      colorPt: "Pac-Man",
      colorEn: "Pac-Man",
      releaseDate: new Date("1982-03-01"),
      limitedEdition: true,
      editionName: "Pac-Man Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-pacman.webp",
    },
    {
      variantSlug: "atari2600-4-switch",
      slug: "atari2600-space-invaders",
      colorPt: "Space Invaders",
      colorEn: "Space Invaders",
      releaseDate: new Date("1980-01-01"),
      limitedEdition: true,
      editionName: "Space Invaders Limited",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/2600-spaceinvaders.webp",
    },

    // Atari 2600 Edições de Retailers
    {
      variantSlug: "atari2600-4-switch",
      slug: "atari2600-sears-telegames",
      colorPt: "Sears TeleGames",
      colorEn: "Sears TeleGames",
      releaseDate: new Date("1979-01-01"),
      limitedEdition: true,
      editionName: "Sears Exclusive",
      material: "Madeira plástica",
      finish: "Texturizado",
      imageUrl: "images/skins/atari/2600-sears.webp",
    },

    // Atari 7800 Edições Especiais
    {
      variantSlug: "atari7800-standard",
      slug: "atari7800-xe",
      colorPt: "XE Game System",
      colorEn: "XE Game System",
      releaseDate: new Date("1987-01-01"),
      limitedEdition: true,
      editionName: "XE Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/7800-xe.webp",
    },

    // Atari 5200
    {
      variantSlug: "atari5200-standard",
      slug: "atari5200-black",
      colorPt: "Preto",
      colorEn: "Black",
      releaseDate: new Date("1982-11-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/5200-black.webp",
    },
    {
      variantSlug: "atari5200-standard",
      slug: "atari5200-four-port",
      colorPt: "4 Portas",
      colorEn: "4-Port Model",
      releaseDate: new Date("1982-11-01"),
      limitedEdition: false,
      editionName: null,
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/5200-4port.webp",
    },
    {
      variantSlug: "atari5200-standard",
      slug: "atari5200-two-port",
      colorPt: "2 Portas",
      colorEn: "2-Port Model",
      releaseDate: new Date("1983-01-01"),
      limitedEdition: true,
      editionName: "Revised Edition",
      material: "Plástico ABS",
      finish: "Brilhante",
      imageUrl: "images/skins/atari/5200-2port.webp",
    },
  ];

  const createdSkins: Record<string, unknown> = {};

  for (const skin of skinDefinitions) {
    const variant = variants[skin.variantSlug];
    if (!variant) {
      throw new Error(`Variante não encontrada: ${skin.variantSlug}`);
    }

    const descriptionPt =
      skin.limitedEdition && skin.editionName
        ? `${skin.editionName} (${skin.material}, ${skin.finish})`
        : `${skin.colorPt} (${skin.material}, ${skin.finish})`;

    const descriptionEn =
      skin.limitedEdition && skin.editionName
        ? `${skin.editionName} (${skin.material}, ${skin.finish})`
        : `${skin.colorEn} (${skin.material}, ${skin.finish})`;

    const createdSkin = await db.skin.upsert({
      where: { slug: skin.slug },
      update: {},
      create: {
        slug: skin.slug,
        consoleVariantId: variant.id,
        releaseDate: skin.releaseDate,
        limitedEdition: skin.limitedEdition,
        editionName: skin.editionName,
        material: skin.material,
        finish: skin.finish,
        imageUrl: skin.imageUrl,
        translations: {
          create: [
            {
              locale: "pt",
              name: skin.colorPt,
              description: descriptionPt,
            },
            {
              locale: "en",
              name: skin.colorEn,
              description: descriptionEn,
            },
          ],
        },
      },
    });

    createdSkins[skin.slug] = createdSkin;
  }

  return createdSkins;
}
